language: python
python:

  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install
# command to run tests
script:
  - nosetests # or py.test for Python versions 3.5 and below
