# This file contains a default configuration file in YAML 1.2 format
minhash:
    jgi_server_url: 'https://refseq-sketch.jgi-psf.org/sketch'
    superkingdom :
        2: "Bacteria"
        2157: "Archaea"
        2759: "Eukaryota"
        12884: "Viroids"
        10239: "Viruses"
    noncellular :
        39759: "Deltavirus"
        35237: "dsDNA viruses, no RNA stage"
        35325: "dsRNA viruses"
        1910928: "Genomoviridae"
        35268: "Retro-transcribing viruses"
        12877: "Satellites"
        29258: "ssDNA viruses"
        439488: "ssRNA viruses"
        1714266: "Virus families not assigned to an order"
        686617: "unassigned viruses"
        451344: "unclassified archaeal viruses"
        12333: "unclassified bacterial viruses"
        1922347: "unclassified RNA viruses"
        552364: "unclassified virophages"
        12429: "unclassified viruses"
        12884: "Viroids"
